apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: ddpn08
  name: samba-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  nfs:
    server: 192.168.1.200
    path: /exports/slow-drive-01/smb
  storageClassName: samba-pv-class
