apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: ddpn08
  name: samba-pvc
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: samba-pv-class
