apiVersion: v1
kind: Service
metadata:
  namespace: ddpn08
  name: samba-service
spec:
  selector:
    app: samba
  ports:
    - name: browsing
      port: 139
      targetPort: 139
    - name: file
      port: 445
      targetPort: 445
  type: LoadBalancer
  loadBalancerIP: 192.168.1.220
